language: java
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "akhiltn"
      - git config --local user.email "tnakhil@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  user: "akhiltn"
  password: "aki701107"
  file: "target/NumberGenerator*.jar"
  skip_cleanup: true
