language: java
deploy:
  provider: releases
  api_key:
    secure: "150c25b1061a6a9710732519e42619d4ec2609cc"
  file: "target/NumberGenerator-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
